[options]
admin_passwd = masterpassword
default_productivity_apps = True
longpolling_port = 8072

# Database settings
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = realestate 
db_maxconn = 64
db_sslmode = disable
db_template = template0


addons_path = /etc/odoo/addons,/etc/odoo/custom_addons
data_dir = /var/lib/odoo

# HTTP Service Configuration
http_enable = True
http_interface = 0.0.0.0
http_port = 8069
proxy_mode = True
xmlrpc = True
xmlrpc_interface = 0.0.0.0
xmlrpc_port = 8069

# Web interface Configuration
list_db = True
dbfilter = 

# Logging Configuration
log_db = True
log_db_level = warning
log_handler = [':INFO']
# You can change to "info" for less verbose logs
log_level = debug
logfile = /var/log/odoo/odoo.log
syslog = False


# Performance Tuning
workers = 0
max_cron_threads = 1
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

# Miscellaneous
email_from = False
without_demo = True
demo = {}
server_wide_modules = base,web

